-- Replicas --

// alias -> address
comp1     3.115.105.65
comp2 13.39.158.100
comp3      3.147.81.182
//comp4      15.157.58.138
//comp5     56.125.101.228

-- Clients --

// alias -> address
client1      13.214.130.40
client2 13.200.6.197
client3 3.8.200.88
client4      54.81.143.41
client5   54.193.241.116
client6      15.228.89.211
client7      18.183.205.244
//client8      13.55.71.49
//client9      108.129.120.96
//client10      13.42.26.157

-- Master --

// alias -> address
master 18.180.59.236

masterPort: 7077


protocol: SwiftPaxos

// Replicas
noop:       false // do not execute
thrifty:    false
optread:    false
leaderless: false
fast:       true

//Comments: Just because slowPaths is incremented, doesnt mean its actually slow
// Clients
reqs:        1000
runTime:     none // 5min
writes:      100
conflicts:   10
commandSize: 1000
clones:      9
key:         42 // conflicting key

pipeline: false
pendings: 10000

-- Apply to ap-northeast-1 --
waitClosest: true

-- Apply to us-west-1 --
waitClosest: true


// Used to find the closest replica to client.
// This is a mapping
// Example:
// clients located on ap-east-1 will say that the closest replica (if exists) will be on ap-northeast-1 
// The 5 server_alias are the replicas 
-- Proxy --
server_alias comp1
client1
client7 (local)

server_alias comp2
client2
client3

server_alias comp3
client4
client5
client6

//server_alias comp4

//server_alias comp5
---