-- Replicas --

// alias -> address
comp1     35.76.29.174
comp2 18.178.204.223
comp3      18.181.240.189
comp4      57.183.37.144
comp5     13.230.31.220

-- Clients --

// alias -> address
client1      52.196.32.79
client2 54.250.244.5
client3 54.95.192.35
client4      18.182.33.114
client5   35.78.195.19
//client6      localhost
//client7      localhost
//client8      13.55.71.49
//client9      108.129.120.96
//client10      13.42.26.157

-- Master --

// alias -> address
master 18.183.114.118

masterPort: 7077


protocol: SwiftPaxos

// Replicas
noop:       false // do not execute
thrifty:    false
optread:    false
leaderless: true
fast:       false

//Comments: Just because slowPaths is incremented, doesnt mean its actually slow
// Clients
reqs:        1000
runTime:     none // 5min
writes:      100
conflicts:   100
commandSize: 1000
clones:      9
key:         42 // conflicting key

pipeline: false
pendings: 10000

-- Apply to ap-northeast-1 --
waitClosest: true

-- Apply to us-west-1 --
waitClosest: true


// Used to find the closest replica to client.
// This is a mapping
// Example:
// clients located on ap-east-1 will say that the closest replica (if exists) will be on ap-northeast-1 
// The 5 server_alias are the replicas 
-- Proxy --
server_alias comp1
client1 (local)

server_alias comp2
client2 (local)

server_alias comp3
client3 (local)

server_alias comp4
client4 (local)

server_alias comp5
client5 (local)
---